### ISSUE TITLE
Not able to get responses to Google sheet when optional questions are not answered.

### ISSUE THREAD

**Issue by Akshaydhane1990** [gsuitedevs/solutions#145] opened 2020-08-24 20:34 UTC
Code where values are changed.

var NEW_REQUEST = [
  '15.6" high Performance Laptop (Windows)',
  '14" high Performance Laptop (Windows)',
  '15.6" high performance Laptop (Linux)',
  '14" lightweight laptop (Windows)',
  'High performance Desktop (Windows)',
  'Regular performance Desktop (linux)',
  'Wired Mouse',
  'Wireless Mouse',
  '18" Monitor',
  '21" Monitor',
  'Laptop Bag',
  'UPS',
  'Pen drive',
  
  
];
var REPAIR_REQUEST = [
  'UPS Battery replacement',
  'Keyboard replacement',
  'Monitor Repair',
  'Mouse Replacement',
  'RAM Upgrade/Replace',
  
];
var SUPPORT_REQUEST = [
  'Not able to Start PC/Laptop',
  'Black Screen when start',
  'Blue Screen when start',
  'Hang/Screen Stuck',
  'Software not working',
  'New software Installation',
  
];

  var form = FormApp.create('Equipment Requests')
      .setCollectEmail(true)
      .setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId())
      .setLimitOneResponsePerUser(false);
  form.addTextItem().setTitle('Employee name').setRequired(true);
  form.addTextItem().setTitle('Desk location').setRequired(true);
  form.addDateItem().setTitle('Due date').setRequired(true);
  form.addListItem().setTitle('NEW_REQUEST').setChoiceValues(NEW_REQUEST);
  form.addListItem().setTitle('REPAIR_REQUEST').setChoiceValues(REPAIR_REQUEST);
  form.addListItem().setTitle('SUPPORT_REQUEST').setChoiceValues(SUPPORT_REQUEST);

/**
 * Handle new form submissions to trigger the workflow.
 *
 * @param {Object} event - Form submit event
 */
function onFormSubmit_(event) {
  var response = mapResponse_(event.response);
  sendNewEquipmentRequestEmail_(response);
  var equipmentDetails = Utilities.formatString('%s\n%s\n%s',
      response['NEW_REQUEST'],
      response['REPAIR_REQUEST'],
      response['SUPPORT_REQUEST']);
  var row = ['New',
    '',
    response['Desk location'],
    response['Employee name'],
    response['Desk location'],
    equipmentDetails,
    response['email']];
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Pending requests');
  sheet.appendRow(row);
}

**Comment by sqrrrl** [comment] 2020-08-24 21:35
Since this looks to be a modified form of a solution and not much information provided about the issue, suggest taking a little time to narrow down the cause.

* Does the original solution exhibit the problem?
* What's the least amount of changes that causes the problem?
* What are the steps to reproduce?

Also, it's not at all clear what the actual problem is. Looking at the code, all the questions are marked as required, so not sure what you mean by optional questions...

**Comment by Akshaydhane1990** [comment] 2020-08-25 05:29
1. Original solution also work only if i fill all the questions in google forms.
2. i have changed only given variables. 
   NEW_REQUEST,
   REPAIR_REQUEST,
   SUPPORT_REQUEST,

3. i dint get your question.

i have setup trigger also on form submit

**Comment by sqrrrl** [comment] 2020-08-25 15:23
Looks like the issue is line ~111 in the original -- the string format fails if an option isn't selected. Will update the original.

**Comment by sqrrrl** [comment] 2020-08-31 16:16
Fixed.

**Closed by sqrrrl** 2020-08-31 16:16 UTC
Labels: bug
